en:
  name: "Security Compliance"
  slug: "security-compliance"
et:
  name: "Turvalisus ja nõuetele vastavus"
  slug: "turvalisus-ja-nouetele-vastavus"
lv:
  name: "Drošība un atbilstība"
  slug: "drosiba-un-atbilstiba"
ua:
  name: "Безпека та відповідність"
  slug: "bezpeka-ta-vidpovidnist" 