en:
  name: "Contract Management"
  slug: "contract-management"
et:
  name: "Lepingute haldus"
  slug: "lepingute-haldus"
lv:
  name: "Līgumu pārvaldība"
  slug: "ligumu-parvaldiba"
ua:
  name: "Управління контрактами"
  slug: "upravlinnya-kontraktamy" 