en:
  name: "Doc Automation"
  slug: "doc-automation"
et:
  name: "Dokumendiautomaatika"
  slug: "dokumendiautomaatika"
lv:
  name: "Dokumentu automatizācija"
  slug: "dokumentu-automatizacija"
ua:
  name: "Автоматизація документів"
  slug: "avtomatizatsiya-dokumentiv" 