en:
  name: "Agrello Features"
  slug: "agrello-features"
et:
  name: "Agrello funktsioonid"
  slug: "agrello-funktsioonid"
lv:
  name: "Agrello funkcijas"
  slug: "agrello-funkcijas"
ua:
  name: "Agrello можливості"
  slug: "agrello-mozhlivosti" 